contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
baseurl = "https://skarlso.github.io/"
title = "Ramblings of a build engineer"
canonifyurls = true
disqusShortname = "hannibalDisqus"
Paginate = 10

[taxonomies]
    category = "categories"
    tag = "tags"

[params]
    sidebartitle = "Ramblings..."
    sidebartagline = "...of a build engineer."
    highlightStyle = "true"
    hideShareOptions = true
    twitterName = "Skarlso"
    githubName = "Skarlso"
    google_analytics = "UA-69463020-2"

[[menu.social]]
    pre = "<i class='fa fa-fort-awesome fa-3x'></i>"
    url = "http://skarlso.com"
    identifier = "site"
