contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "https://skarlso.github.io/"
title: "Ramblings of a build engineer"
canonifyurls: true
params:
    sidebartitle : "Ramblings..."
    sidebartagline : "...of a build engineer."
    sidebarphoto : "img/sidebar.png"
