contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
baseurl = "https://skarlso.github.io/"
title = "Ramblings of a cloud engineer"
theme = "terminal"
contentTypeName = "blog"
canonifyurls = true
disqusShortname = "hannibalDisqus"
Paginate = 10
preserveTaxonomyNames = true
enableRobotsTXT = true
pluralizeListTitles = false
googleAnalytics = "UA-69463020-2"

[taxonomies]
    category = "categories"
    tag = "tags"

[params]
    themeColor = "green"
    # Sets the meta tag description
    description          = "Ramblings of a Cloud Engineer"
    # Sets the navbarTitle that appears in the top left of the navigation bar
    navbarTitle          = "Hello, Clarice!"
    # Sets where "View More Posts" links
    viewMorePostLink     = "/blog/"
    dynamicTitles        = true
    socialAppearAtBottom = true
    socialShare          = true
    socialShareTwitter   = true
    socialShareGoogleplus = true
    socialShareFacebook  = true
    socialShareReddit    = true
    socialShareLinkedin  = true
    disable_highlight = false # set to true to disable Highlight
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["json", "yaml", "css", "go", "bash"]
    highlightjsTheme = "github"

[social]
    github = "Skarlso"
    linkedin = "brautigamgergely"
    twitter = "Skarlso"

[params.postAmount]
# Sets the number of recent posts to show in the sidebar. The default value is 5.
    sidebar = 5

[[menu.main]]
    name = "Home"
    url = "/"
    identifier = "fa fa-home"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    identifier = "fa fa-newspaper-o"
    weight = 2

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    identifier = "fa fa-sitemap"
    weight = 3
