baseURL = "https://skarlso.github.io/"
# languageCode = "en-us"
# defaultContentLanguage = "en"
title = "Ramblings of a cloud engineer"
theme = "meme"
# enableGitInfo = true
# pygmentsCodefences  = true
# pygmentsUseClasses  = true
# hasCJKLanguage = true  # If Chinese/Japanese/Korean is your main content language, enable this to make wordCount works right.
# rssLimit = 10  # Maximum number of items in the RSS feed.
# googleAnalytics = "UA-69463020-2"


[services.rss]
  limit = 10

[author]
  name = "Gergely Brautigam"
  website = "https://gergelybrautigam.com"
  twitter = "https://twitter.com/skarlso"
  github = "https://github.com/Skarlso"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  # Metadata mostly used in document's head
  homeLayout = "posts"
  homeTitle = "Welcome to my little corner of the internet"
  footerCopyright = '[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en)'
  displayPosts = true
  enableDisqus = true
  disqusShortname = "hannibalDisqus"
  enableGoogleAnalytics = true
  trackingCodeType = "gtag"
  trackingID = "UA-69463020-2"
  postMetaDateFormat = "2006.1.2"
  listDateFormat = "January 2"
  listDatePosition = "right"
  categoryBy = "categories"
  enableTOC = false
  fofPoster = ""
[menu]

  [[menu.main]]
    name = "blog"
    url = "blog/"
    weight = 10
